text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "webserver:/home/admin/sites/michaelbarton.me.uk/projects/scaffolder"
    options: [ '-gpPrvz' ]
site:
  title: "Scaffolder"
  subtitle: "Genome scaffolding for human beings"
  url: "http://www.michaelbarton.me.uk/projects/scaffolder"
  analytics_token: "UA-1362555-4"
  navigation:
    'api documentation':    "http://rubydoc.info/gems/scaffolder/frames"
    'unix manual pages':    "/man/"
    'contribute':           "/contribute/"
    'mailing list':         "http://groups.google.com/group/scaffolder/topics"
    'getting started':      "/getting-started/"
    'scaffold file format': "/man/scaffolder-format/"
author:
  url: "http://www.michaelbarton.me.uk"
  name: "Michael Barton"
